In [2]:
import numpy as np
import pandas as pd

In [126]:
#question 1.1
x = [[1,2,3],[4,5,6]]
np.array(x)

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
#question 1.2
np.arange(1,7).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
#question 1.3
np.arange(2,101,2).mean()

51.0

In [48]:
#question 1.4
np.random.random((3,3,3)).min(),np.random.random((3,3,3)).max()


(0.10590760718779213, 0.9952995676778876)

In [39]:
#question 1.5
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [36]:
#question 1.6
np.arange(5,35,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [26]:
#question 1.7
np.random.randint(10, size=(10, 10)).itemsize*np.random.randint(10, size=(10, 10)).size

400

In [76]:
#question 1.8
np.random.seed(8),np.random.randint(11,size=10)

(None, array([ 3,  4,  1,  9,  5, 10,  8,  3,  8,  0]))

In [86]:
np.random.randint(1, [6],size=10)

array([2, 5, 4, 1, 4, 1, 3, 4, 1, 2])

In [82]:
#question 1.9
np.arange(10,50),np.arange(49,9,-1)

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49]),
 array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
        32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10]))

In [59]:
#question 1.10
np.random.seed(0)
np.random.uniform(0,1,size=((3,2)))

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

In [30]:
#question 1.11
np.zeros((5,5))+ np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [122]:
#question 1.12
x =np.ones((5,5))
print(x)
np.pad?
np.pad(x,pad_width=1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [54]:
#question 1.13
x=np.diag([1,2,3,4,5])
print(x)
y=np.diag(x)
z=np.diag(y,k=-1)
a,b=np.hsplit(z,[5])
d,e=np.vsplit(a,[5])
print(d)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [124]:
#question 1.14
x =np.zeros((8,8))
print(x)
np.pad?
np.pad(x,pad_width=1,constant_values=1)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
#question 1.15
np.random.seed(0)
x=np.random.uniform(0,20,20)
print(x)
a=x.astype(int)
a

[10.97627008 14.30378733 12.05526752 10.89766366  8.47309599 12.91788226
  8.75174423 17.83546002 19.27325521  7.66883038 15.83450076 10.5778984
 11.36089122 18.51193277  1.42072116  1.74258599  0.40436795 16.65239691
 15.56313502 17.40024296]


array([10, 14, 12, 10,  8, 12,  8, 17, 19,  7, 15, 10, 11, 18,  1,  1,  0,
       16, 15, 17])

In [63]:
#question 2.1
x=np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
a=np.where(x==1)
c=0
for i in a[0]:
    c=c+1
    if(c==5):
        print(i)


(array([ 0,  2,  3,  7,  8, 10, 11], dtype=int64),)
8


In [87]:
#question2.2
x=np.arange(1,10)
a,b,c=np.split(x,[4,6])
print(a)
print(b)
print(c)

[1 2 3 4]
[5 6]
[7 8 9]


In [86]:
#question2.3
x = np.arange(16.).reshape((4,4))
print(x)
a,b=np.split(x,[2],axis=1)
print(abs(a),abs(b))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
[[ 0.  1.]
 [ 4.  5.]
 [ 8.  9.]
 [12. 13.]] [[ 2.  3.]
 [ 6.  7.]
 [10. 11.]
 [14. 15.]]


In [19]:
#question 2.4
x = np.array([[5,10,15],

 [20,25,30],

 [35,40,45]]
)
x
a,b=np.hsplit(x,[1])
c,d=np.vsplit(b,[2])
print(c)
p,q,r=np.vsplit(a,[1,2])
print(q)

[[10 15]
 [25 30]]
[[20]]


In [28]:
#question 2.5
x = np.array([[ 1,2,3],[ 4,5,6]])
y = np.array([[ 7,8,9],[10,11,12]])
np.concatenate([x,y],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [45]:
#question 2.6
np.random.seed(0)
arr=np.random.randint(11,size=(5,3))
print(arr)
i=0
for i in arr:
    a,arr=np.vsplit(arr,[1])
    print(np.min(a)/np.max(a))
    i=i+1

[[ 5  0  3]
 [ 3  7  9]
 [ 3  5  2]
 [ 4  7  6]
 [ 8  8 10]]
0.0
0.3333333333333333
0.4
0.5714285714285714
0.8


In [69]:
#question2.7
x=np.random.random((5,5))
print("before normalization:")
print(x)
maxi,mini=x.max(),x.min()
x=(x-mini)/(maxi-mini)
print("after normalization")
print(x)

before normalization:
[[0.78364425 0.5000263  0.05037006 0.69909807 0.9923964 ]
 [0.26726254 0.67909062 0.86428144 0.75084425 0.96448977]
 [0.55424244 0.2123905  0.22244322 0.21874937 0.56957353]
 [0.45210904 0.97023668 0.68054469 0.08529557 0.05641833]
 [0.4878377  0.88100456 0.97640439 0.61765792 0.54249878]]
after normalization
[[0.77840094 0.47732873 0.         0.68865167 1.        ]
 [0.23024036 0.66741293 0.86400066 0.74358238 0.97037595]
 [0.53488141 0.17199141 0.1826628  0.17874162 0.55115601]
 [0.42646257 0.97647654 0.66895649 0.03707488 0.0064205 ]
 [0.46439004 0.88175295 0.98302382 0.60219957 0.52241503]]


In [72]:
#question2.8
x=np.arange(3)
y=np.arange(3,7)
z=np.arange(7,9)
print(x,y,z)
np.concatenate([x,y,z])

[0 1 2] [3 4 5 6] [7 8]


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
#question2.9
np.random.seed(0)
x=np.random.randint(0,100,20)
print(x)
for i in range(x.size):
    if(x[i]>=15 and x[i]<=55):
        a=np.insert(a,,x[i])
print(a)

[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]


IndexError: index 7 is out of bounds for axis 0 with size 1

In [6]:
#question2.10
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

c=np.where(a==b)
print(c[0])

[1 3 5 7]


In [10]:
#question2.11
x=np.arange(20)
x
for i in range(x.size):
    if (x[i]%2!=0):
        x[i]=-1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1])

In [8]:
#question 2.12
x=np.random.randint(10,size=((3,4,3,4)))
x.sum(axis=3).sum(axis=2)

array([[65, 56, 57, 58],
       [48, 33, 48, 53],
       [57, 47, 43, 59]])