In [2]:
# Homw Work 2-- Shubham Singh, 002762502

In [3]:
import numpy as np
import pandas as pd

In [5]:
#1 - 1)
#Put 3 random numbers (which can be same value, like 6) to a 2D 10x10 zero array in random positions.  

np.random.seed(10)
num = np.random.choice(6,3)
print("Three random values are :" , num)
num2 = np.zeros((10,10))
np.put(num2,num,[6,6,6],mode='raise')
print (num2)

Three random values are : [1 5 4]
[[0. 6. 0. 0. 6. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [10]:
#1 - 2)
#Create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. Please use the numpy indexing and slicing approaches to implement

arr_zero=np.zeros((4,4))
arr_zero[::2, 1::2] = 1
arr_zero[1::2, ::2] = 1
print("The Desired Matrix is :\n", arr_zero)

The Desired Matrix is :
 [[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [53]:
#1 - 3.1)
#Write a 6x6 matrix for multiplication table:
#by using numpy broadcasting     

Array1 = np.zeros((6,6))
Array1 = Array1 +np.arange(1,7)
Array2 = np.arange(1,7).reshape(6,1)
Result_array = Array1*Array2
Result_array.astype(int)       

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [58]:
#1 - 3.2)
#by using Python nested for-loop

for m in range(0,6):
    for n in range(0,6):
        Array1[m][n]=(m+1)*(n+1)
Array1.astype(int)

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [16]:
#2 -1)
#Convert the list of 26 letters of the alphabet to the index of the Dataframe, and assign 26 random integer numbers Print out the first 5 rows.   


dataf = pd.DataFrame(np.random.randint(1,100,26),index=list('abcdefghijklmnopqrstuvwxyz'))
alphabet_arr=dataf.head(5)
print('The first 5 rows are \n', alphabet_arr)

The first 5 rows are 
     0
a  86
b  23
c  12
d  13
e  93


In [60]:
#2  -2)
#Construct the following DataFrame and print it out. Use "iloc" to convert the first column of this DataFrame as a Series. 4 points

df2 = pd.DataFrame({'class 1':[1,2,3,4,7,11],'class 2':[4,5,6,9,5,0],'class 3':[7,5,8,12,1,11]})
print('\nDataFrame :\n',df2)
first_col= (df2.iloc[: , 0:1]).unstack()
print('\n\nThe First Column as Series is \n',first_col,'\nThe Data Type is \n',type(first_col))


DataFrame :
    class 1  class 2  class 3
0        1        4        7
1        2        5        5
2        3        6        8
3        4        9       12
4        7        5        1
5       11        0       11


The First Column as Series is 
 class 1  0     1
         1     2
         2     3
         3     4
         4     7
         5    11
dtype: int64 
The Data Type is 
 <class 'pandas.core.series.Series'>


In [28]:
#2 --3.1) 
#Select all columns, except one given column 'class3', and print out the result.

df2.iloc[:,0:2] #not Printing it out seperately as it changing the format

class 1  class 2
0        1        4
1        2        5
2        3        6
3        4        9
4        7        5
5       11        0

In [29]:
#2 --3.2) 
#Remove first 3 rows of the DataFrame and print it out.

df2.iloc[3: , :]  #not Printing it out seperately as it changing the format

class 1  class 2  class 3
3        4        9       12
4        7        5        1
5       11        0       11

In [30]:
#2 --3.2)  
#Remove last 3 rows of the DataFrame and print it out.

df2.iloc[:3, :]  #not Printing it out seperately as it changing the format

class 1  class 2  class 3
0        1        4        7
1        2        5        5
2        3        6        8

In [31]:
#2 --4)
#Compute the Euclidean distance between two series (points) p1 and p2:        

p1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
p2 = pd.Series([8, 9, 10, 11, 12, 7, 6, 5, 4, 3])
Euc_Dist=((p1-p2)**2).sum()**0.5
print('Euclidean Distance is',Euc_Dist)

Euclidean Distance is 18.16590212458495


In [34]:
#2 --5.1)
#Create a DataFrame df: the name of 4 columns is pqrs respectively, the name of 10 indexes is abcdefghij respectively. The values are randomly distributed in [1,100) and the seed is set as 42

np.random.seed(42)
df = pd.DataFrame(np.random.randint(1,100,size=(10,4)), columns=list('pqrs'), index=list('abcdefghij'))
print('DataFrame is:\n',df)

#2 --5.2) 
#Create a new column such that, each row of this df contains the row number of nearest row-record by Euclidean distance.

nearest_rows = []
nearest_distance = []

for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    eu_dists = {} 
    for j, contestant in rest.iterrows():
        eu_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    
    nearest_rows.append(max(eu_dists, key=eu_dists.get))
    nearest_distance.append(max(eu_dists.values()))

df['New_Row'] = nearest_rows
df['Distance'] = nearest_distance
df

DataFrame is:
     p   q   r   s
a  52  93  15  72
b  61  21  83  87
c  75  75  88  24
d   3  22  53   2
e  88  30  38   2
f  64  60  21  33
g  76  58  22  89
h  49  91  59  42
i  92  60  80  15
j  62  62  47  62


p   q   r   s New_Row  Distance
a  52  93  15  72       d       117
b  61  21  83  87       d       107
c  75  75  88  24       d        98
d   3  22  53   2       g       123
e  88  30  38   2       a       103
f  64  60  21  33       b        91
g  76  58  22  89       d       123
h  49  91  59  42       d        92
i  92  60  80  15       a       101
j  62  62  47  62       d        93

In [37]:
#2 --6)
#Create a DataFrame with rows as strides from a given series : L=pd.Series(range(15))
Seri = pd.Series(range(15))
def strides_func(a,slen=5 , wlen=5):
    n= ((a.size-wlen)//slen)+1
    return np.array([a[s:(s+wlen)] for s in np.arange(0,a.size,slen)[:n]])
print(strides_func(Seri,slen=2,wlen=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]


In [38]:
#2  -7.1)
#Create a DataFrame, the name of columns is abcde respectively, the values ranges [0,20)
np.random.seed(0)
df7 = pd.DataFrame(np.random.randint(0,20,size=(5,5)), columns=list('abcde')) 
df7

a   b   c   d  e
0  12  15   0   3  3
1   7   9  19  18  4
2   6  12   1   6  7
3  14  17   5  13  8
4   9  19  16  19  5

In [39]:
#2  -7.2)
#Interchange columns 'a' and 'c' 
col_list = list(df7)
col_list[2],col_list[0]=col_list[0],col_list[2]
df8 =df7[col_list]
df8

c   b   a   d  e
0   0  15  12   3  3
1  19   9   7  18  4
2   1  12   6   6  7
3   5  17  14  13  8
4  16  19   9  19  5

In [40]:
#2 - 7.3)
#Create a generic function to interchange arbitrary two columns 
def swap_columns(df7, col1, col2):
    col_list = list(df7.columns)
    x ,y =col_list.index(col1) , col_list.index(col2)
    col_list[y], col_list[x] = col_list[x], col_list[y]
    df7 = df7[col_list]
    return df7
df2 = swap_columns(df7, 'd', 'a')
df2

d   b   c   a  e
0   3  15   0  12  3
1  18   9  19   7  4
2   6  12   1   6  7
3  13  17   5  14  8
4  19  19  16   9  5

In [41]:
#2  -7.4)
#Sort the columns in reverse alphabetical order, that is column 'e' first through column 'a' last.
reverse=df7.columns[::-1]
df7[reverse]

e   d   c   b   a
0  3   3   0  15  12
1  4  18  19   9   7
2  7   6   1  12   6
3  8  13   5  17  14
4  5  19  16  19   9

In [42]:
#2  -8) 
#Create a TimeSeries starting ‘2021-01-01’ and 10 weekends (Saturdays) after that having random numbers as values. 
np.random.seed(100)
Sats = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
print('The desired Output is:',Sats)

The desired Output is: 2000-01-01    9
2000-01-08    9
2000-01-15    4
2000-01-22    8
2000-01-29    8
2000-02-05    1
2000-02-12    5
2000-02-19    3
2000-02-26    6
2000-03-04    3
Freq: W-SAT, dtype: int32


In [43]:
#2  -9.1)
#Create a Pandas time series with missing dates (from 2021-01-01 to 2021-01-08) and values, shown as below
np.random.seed(10)
Miss_Dates = pd.Series([1.0, 10.0,3.0,np.nan],index= pd.to_datetime(['01/01/2021', '01/03/2021','01/06/2021','01/08/2021']))
print(Miss_Dates)

2021-01-01     1.0
2021-01-03    10.0
2021-01-06     3.0
2021-01-08     NaN
dtype: float64


In [48]:
#2  -9.2)
#Make all missing dates appear and fill up with value from previous date, shown as below.  
print(Miss_Dates.fillna(method='ffill'))

#Make all missing dates appear and fill up with value from previous date, shown as below.  
Fill_all=Miss_Dates.resample('D').ffill().ffill()
print('\nAll Filled Values are\n',Fill_all)

2021-01-01     1.0
2021-01-03    10.0
2021-01-06     3.0
2021-01-08     3.0
dtype: float64

All Filled Values are
 2021-01-01     1.0
2021-01-02     1.0
2021-01-03    10.0
2021-01-04    10.0
2021-01-05    10.0
2021-01-06     3.0
2021-01-07     3.0
2021-01-08     3.0
Freq: D, dtype: float64


In [49]:
#2 - 10.1) 
#Create a DataFrame ‘df’: the indexes are integer from 0 to 8 (9 rows); the columns are ‘fruit’, ‘taste’, ‘price’; the items of ‘fruit’ are: apple, banana, orange, respectively and repeating 3 times. The ‘taste’ ranges [0,1). The price is integer and ranges [1, 15). The seed of random values is set as 100. 

np.random.seed(100)
fruit = pd.Series(['apple', 'banana', 'orange']*3 , index = np.arange(0,9))
taste = pd.Series(np.random.rand(9))
price = pd.Series(np.random.randint(1,15,size=[9]))
#print(fruit,taste,price)
df10 = pd.DataFrame({'Fruit':fruit, 'Taste':taste ,'Price': price})
df10

Fruit     Taste  Price
0   apple  0.543405      9
1  banana  0.278369      5
2  orange  0.424518     12
3   apple  0.844776     13
4  banana  0.004719     11
5  orange  0.121569      1
6   apple  0.670749     12
7  banana  0.825853     10
8  orange  0.136707     14

In [50]:
#2  -10.2) 
#Find the second largest value of 'taste' for 'banana' (Hint: you can use groupby)   
df10.groupby('Fruit').get_group('banana').sort_values('Taste')[1:2]['Taste']

1    0.278369
Name: Taste, dtype: float64

In [51]:
#2 -10.3)
#Compute the mean price of every fruit, while keeping the fruit as another column instead of an index.  
df10.groupby('Fruit').mean('price')['Price'].reset_index()

Fruit      Price
0   apple  11.333333
1  banana   8.666667
2  orange   9.000000